Repository osuperu/osu-peru-bot, pull requests merged in 2022-09, with the labels that each got.

#14 Add slash command /forcedelink
  src/server/discord/commands/force-delink.ts
  src/server/discord/responses/force-delink.ts
Labels: enhancement

#15 Add vscode task to preview the client with vite
  .vscode/tasks.json
Labels: enhancement

#17 Fix null star rating when posting a new map notification with the tracking
  src/server/scripts/mapping-tracking.ts
Labels: bug

#18 Replace dino png asset with an svg
  src/client/vue/assets/dino.png
  src/client/vue/assets/dino.svg
  src/client/vue/layouts/error-item.vue
  src/client/vue/layouts/events-item.vue
  src/client/vue/layouts/home-item.vue
Labels: enhancement

#25 Improve error handling
  src/server/app.ts
  src/server/discord/commands-manager.ts
  src/server/discord/commands/bn-stats.ts
  src/server/discord/commands/compare.ts
  src/server/discord/commands/force-delink.ts
  src/server/discord/commands/open-bns.ts
  src/server/discord/commands/osu-stats.ts
  src/server/discord/commands/recent.ts
  src/server/discord/commands/top.ts
  src/server/discord/commands/track-mapping.ts
  src/server/discord/commands/untrack-mapping.ts
  src/server/discord/discord-client.ts
  src/server/discord/models/slash-command.ts
  src/server/discord/responses/error.ts
Labels: enhancement

#26 Re-add the slash commands that were deleted in the rewrite
  src/server/app.ts
  src/server/discord/commands/mapping-stats.ts
  src/server/discord/commands/run-script.ts
  src/server/discord/responses/mapping-stats.ts
Labels: enhancement

#27 Add a temporary script to remove slash commands that no longer exist
  src/server/scripts/delete-old-commands.ts
Labels: enhancement

#28 Improve mapping tracking error handling
  src/server/scripts/mapping-tracking.ts
Labels: enhancement

#29 Fix star rating not being displayed in the mapping tracking event
  src/server/scripts/mapping-tracking.ts
Labels: bug, enhancement

#30 Improve logging and osu!api v2 handling
  package.json
  src/server/app.ts
  src/server/discord/discord-client.ts
  src/server/util/api/osu-api.ts
  yarn.lock
Labels: bug, enhancement

#32 Add list-mapping-track slash command
  src/server/discord/commands/list-mapping-tracking.ts
  src/server/discord/responses/list-mapping-tracking.ts
Labels: enhancement

#33 Add total pages to slash command list-mapping-tracking
  src/server/discord/commands/list-mapping-tracking.ts
  src/server/discord/responses/list-mapping-tracking.ts
Labels: enhancement
